# 你的 GitHub 仓库地址（Fork 后的地址）
gitRepoUrl: https://github.com/zhujx001/nav

# 你的分支名称（通常是 main）
branch: main

# 如果使用 GitHub Pages，必须设为 true；Netlify/Vercel 设为 false
hashMode: false

# Netlify 服务器会自动分配地址，保持为空
address: ''

# 只有自有服务器部署才需要密码，Netlify 不需要
password: ''

# Netlify 端口默认会分配，不需要手动设置
port: ''

# 收录通知邮箱（可选，如果不需要邮件通知，可以删除）
email: 'zhujx001@gmail.com'

# Netlify 不支持 SMTP，如果你不需要邮件通知，可以删除 `mailConfig`
mailConfig: {}

# 存储图片的仓库，必须是公开的（你的 `image` 仓库）
imageRepoUrl: 'https://github.com/zhujx001/image?branch=main'
